Improve sload loaders-phase II
unicef/etools-datamart pull request #348
Opened 2024-05-31 21:52 UTC by hbarisik

2024-07-30 15:07 UTC, emaciupe requested changes
@hbarisik I wouldn't remove the get_fr_numbers method unless it was requested - as perhaps it is used.

2024-07-30 15:07 UTC, emaciupe commented on src/etools_datamart/apps/mart/data/models/partners_interventionbudget.py
> -    def get_fr_numbers(self, record: PartnersIntervention, values: dict, **kwargs):
@hbarisik why was this removed?

2024-07-30 15:07 UTC, emaciupe commented on docker-compose-dev.yml
> +  #NOTE: prp db server can be launched externally
@hbarisik please remove local setup changes

2024-07-30 16:04 UTC, hbarisik commented on src/etools_datamart/apps/mart/data/models/partners_interventionbudget.py
> -    def get_fr_numbers(self, record: PartnersIntervention, values: dict, **kwargs):
Restored with updated implementations. Thank you :-)

2024-07-31 08:04 UTC, emaciupe approved these changes

2024-07-31 08:07 UTC, merged