[ch37970] add additional filter for EtoolsUser based on groups values
unicef/etools-datamart pull request #371
Opened 2024-10-04 13:09 UTC by hbarisik

2024-10-08 15:41 UTC, emaciupe requested changes
Other than that, all looks good

2024-10-08 15:41 UTC, emaciupe commented on src/etools_datamart/api/filtering.py
> +            query = Q() | Q()
@hbarisik should be `query = Q()`

2024-10-09 12:49 UTC, hbarisik commented on src/etools_datamart/api/filtering.py
> +            query = Q() | Q()
Done

2024-10-10 12:10 UTC, emaciupe approved these changes

2024-10-15 09:44 UTC, merged